director_uuid: YOUR_DIRECTOR_UUID

networks:
- name: mysql1
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    reserved:
    - 10.0.0.2-10.0.0.109
    - 10.0.0.130-10.0.0.254
    static:
    - 10.0.0.120
    - 10.0.0.121
    - 10.0.0.122
    - 10.0.0.123
    - 10.0.0.124
    dns:
    - 10.0.0.3
    - 8.8.8.8
    cloud_properties:
      name: YOUR_SUBNET_NAME #This should match your vSphere network name, e.g. "VM Network".
- name: mysql2
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    reserved:
    - 10.0.1.2-10.0.1.109
    - 10.0.1.130-10.0.1.254
    static:
    - 10.0.1.120
    - 10.0.1.121
    - 10.0.1.122
    - 10.0.1.123
    - 10.0.1.124
    dns:
    - 10.0.1.3
    - 8.8.8.8
    cloud_properties:
      name: YOUR_SUBNET_NAME_2 #This should match your vSphere network name, e.g. "VM Network 2".
- name: mysql3
  subnets:
  - range: 10.0.2.0/24
    gateway: 10.0.2.1
    reserved:
    - 10.0.2.2-10.0.2.109
    - 10.0.2.130-10.0.2.254
    static:
    - 10.0.2.120
    - 10.0.2.121
    - 10.0.2.122
    - 10.0.2.123
    - 10.0.2.124
    dns:
    - 10.0.2.3
    - 8.8.8.8
    cloud_properties:
      name: YOUR_SUBNET_NAME_3 #This should match your vSphere network name, e.g. "VM Network 3".

properties:
  cf:
    admin_username: YOUR_CF_ADMIN_USERNAME
    admin_password: YOUR_CF_ADMIN_PASSWORD
    skip_ssl_validation: true
  domain: YOUR_CF_SYSTEM_DOMAIN # The broker registers a route at p-mysql.external_domain
  app_domains:
  - YOUR_CF_APPS_DOMAIN
  nats:
    machines:
      - 10.0.0.5
    password: NATS_PASSWORD_FROM_CF_RELEASE
    user: nats
    port: 4222

meta:
  environment: YOUR_ENVIRONMENT_NAME

jobs:
- name: proxy_z1
  properties:
    proxy:
      api_username: A_USERNAME_YOU_MAKE_UP # Used for basic auth in front of proxy api
      api_password: A_PASSWORD_YOU_MAKE_UP
- name: mysql_z1
  properties:
    admin_password: A_PASSWORD_YOU_MAKE_UP #The admin password for the MySQL server process
- name: cf-mysql-broker_z1
  properties:
    # The username & password cloud controller will use to authenticate with the service broker.
    auth_username: A_USERNAME_YOU_MAKE_UP #eg. cc
    auth_password: A_PASSWORD_YOU_MAKE_UP
    cookie_secret: A_PASSWORD_YOU_MAKE_UP
    services:
    - name: p-mysql
      dashboard_client:
        secret: A_PASSWORD_YOU_MAKE_UP #Secret used by MySQL dashboard to fetch an OAuth token from UAA
