director_uuid: YOUR_DIRECTOR_UUID

networks:
- name: mysql1
  type: manual
  subnets:
  - range: 10.10.32.0/24
    reserved:
      - 10.10.32.2 - 10.10.32.9
      - 10.10.32.130 - 10.10.32.254
    static:
      - 10.10.32.10 - 10.10.32.14
    gateway: 10.10.32.1
    dns:
      - 10.10.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
    cloud_properties:
      subnet: (( properties.template_only.aws.subnet_ids.mysql1 ))
- name: mysql2
  type: manual
  subnets:
  - range: 10.10.33.0/24
    reserved:
      - 10.10.33.2 - 10.10.33.9
      - 10.10.33.130 - 10.10.33.254
    static:
      - 10.10.33.10 - 10.10.33.14
    gateway: 10.10.33.1
    dns:
      - 10.10.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
    cloud_properties:
      subnet: (( properties.template_only.aws.subnet_ids.mysql2 ))
- name: mysql3
  type: manual
  subnets:
  - range: 10.10.34.0/24
    reserved:
      - 10.10.34.2 - 10.10.34.9
      - 10.10.34.130 - 10.10.34.254
    static:
      - 10.10.34.10 - 10.10.34.14
    gateway: 10.10.34.1
    dns:
      - 10.10.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
    cloud_properties:
      subnet: (( properties.template_only.aws.subnet_ids.mysql3 ))
- name: compilation
  type: manual
  subnets:
    - range: 10.10.35.0/24
      name: default_unused
      reserved:
        - 10.10.35.2 - 10.10.35.9
        - 10.10.35.130 - 10.10.35.254
      static:
        - 10.10.35.10 - 10.10.35.14
      gateway: 10.10.35.1
      dns:
        - 10.10.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
      cloud_properties:
        subnet: (( properties.template_only.aws.subnet_ids.compilation ))

properties:
  cf:
    # these come from your cf-release manifest
    admin_username: YOUR_CF_ADMIN_USERNAME
    admin_password: YOUR_CF_ADMIN_PASSWORD
    skip_ssl_validation: false

  domain: YOUR_CF_SYSTEM_DOMAIN # The broker registers a route at p-msyql.external_domain.
  app_domains:
  - YOUR_CF_APPS_DOMAIN
  nats:
    user: nats
    password: NATS_PASSWORD_FROM_CF_RELEASE
    machines:
      - 10.10.80.11
    port: 4222

  template_only:
    aws:
      availability_zone: YOUR_AWS_AVAILABILITY_ZONE_1 #From the EC2 page of the AWS console, like us-east-1a
      availability_zone2: YOUR_AWS_AVAILABILITY_ZONE_2 #From the EC2 page of the AWS console, like us-east-1b
      availability_zone3: YOUR_AWS_AVAILABILITY_ZONE_3 #From the EC2 page of the AWS console, like us-east-1c
      subnet_ids:
        # From VPC/Subnets page of AWS console. Availability zone must match the value set above.
        mysql1: YOUR_SUBNET_ID_1
        mysql2: YOUR_SUBNET_ID_2
        mysql3: YOUR_SUBNET_ID_3
        compilation: YOUR_COMPILATION_SUBNET

meta:
  environment: YOUR_ENVIRONMENT_NAME

jobs:
# Jobs for cf-mysql-release are below
- name: mysql_z1
  properties:
    admin_password: A_PASSWORD_YOU_MAKE_UP #The admin password for the MySQL server process

- name: cf-mysql-broker_z1
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
    # The username & password cloud controller will use to authenticate with the service broker.
    auth_username: A_USERNAME_YOU_MAKE_UP # eg. cc
    auth_password: A_PASSWORD_YOU_MAKE_UP
    cookie_secret: A_PASSWORD_YOU_MAKE_UP
    services:
      - name: p-mysql
        dashboard_client:
          secret: A_PASSWORD_YOU_MAKE_UP #Secret used by MySQL dashboard to fetch an OAuth token from UAA
        plans:
        - name: YOUR_PLAN_NAME
          max_storage_mb: PLAN_SIZE_IN_MB

- name: proxy_z1
  release: cf-mysql
  properties:
    proxy:
      api_username: A_USERNAME_YOU_MAKE_UP
      api_password: A_PASSWORD_YOU_MAKE_UP
